{% set version = "1.0.0a4" %}

package:
  name: cleo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cleo/cleo-{{ version }}.tar.gz
  sha256: a103a065d031b7d936ee88a6b93086a69bd9c1b40fa2ebfe8c056285a66b481d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.0,<2
  run:
    - python >=3.6
    - crashtest >=0.3.1,<0.4
    - pylev >=1.3.0,<2

test:
  imports:
    - cleo
    - cleo.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdispater/cleo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - ocefpaf
    - xylar
