{% set version = "0.8.0" %}

package:
  name: cleo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cleo/cleo-{{ version }}.tar.gz
  sha256: b2d56e93b182358591d0ec46c4f787736378a6a8adf4a6512f72aeb0506de981

build:
  number: 0
  noarch: python
  script:
    # we cannot use poetry to install cleo b/c poetry depends on cleo
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    # - poetry >=1.0.0b2
  run:
    - python
    - clikit >=0.4.0,<0.5.0

test:
  imports:
    - cleo
    - cleo.commands
    - cleo.commands.completions
    - cleo.config
    - cleo.io
    - cleo.testers

about:
  home: https://github.com/sdispater/cleo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
