{% set name = "cleo" %}
{% set version = "1.0.0" %}

package:
  name: cleo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cleo-{{ version }}.tar.gz
  sha256: bb5e4f70db83a597575ec86a1ed8fc56bd80934cfea3db97a23ea50c03b78382

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0a5
  run:
    - python >=3.7,<4.0
    - crashtest >=0.4.1,<0.5.0
    - rapidfuzz >=2.2.0,<3.0.0

test:
  imports:
    - cleo
    - cleo.commands
    - cleo.commands.completions
    - cleo.config
    - cleo.io
    - cleo.testers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-poetry/cleo
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - ocefpaf
    - xylar
