{% set name = "cleo" %}
{% set version = "0.7.6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "99cf342406f3499cec43270fcfaf93c126c5164092eca201dfef0f623360b409" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pastel >=0.1.0,<0.2.0
    - pylev >=1.3,<2.0
  run:
    - python
    - pastel >=0.1.0,<0.2.0
    - pylev >=1.3,<2.0

test:
  imports:
    - cleo
    - cleo.commands
    - cleo.commands.completions
    - cleo.descriptors
    - cleo.exceptions
    - cleo.formatters
    - cleo.helpers
    - cleo.inputs
    - cleo.outputs
    - cleo.questions
    - cleo.styles
    - cleo.testers
    - cleo.validators

about:
  home: https://github.com/sdispater/cleo
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
