{% set name = "cleo" %}
{% set version = "2.2.1" %}

package:
  name: cleo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cleo-{{ version }}.tar.gz
  sha256: d9db0fa3a194efb9caadfe1e718bf48cc48f08b7b1ee8381526ecc67c58856c4

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.1.0,<1.2.0
  run:
    - python >=3.7,<4.0
    - crashtest >=0.4.1,<0.5.0
    - rapidfuzz >=3.0.0,<4.0.0

test:
  imports:
    - cleo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-poetry/cleo
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - ocefpaf
    - xylar
